[default]
address = "127.0.0.1"
port = 8000

[release]
address = "0.0.0.0"
port = 8000

[_release.tls]
certs = "/etc/letsencrypt/live/ozmium.xyz/fullchain.pem"
key = "/etc/letsencrypt/live/ozmium.xyz/privkey.pem"